version: 0.2

phases: 
  install:
    commands:
      - Installing Node 18+ ......
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
      - apt install -y nodejs
  pre_build:
    commands:
      - Installing dependencies
      - npm
  build:
    commands:
      - Testing..... 
      - npm test
      - Building.....
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public