version: 0.2

phases: 
  pre_build:
    commands:
      # Installing NPM......
      - npm install
      # - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      # - apt install -y nodejs
      # runtime-versions:
      # nodejs: 18
  build:
    commands:
      # Testing..... 
      - npm test
      # Building.....
      - npm run build
artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - "**/*"
  discard-paths: no
  base-directory: build