version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      # Installing NPM dependencies......
      - npm install
      # - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      # - apt install -y nodejs

      # Testing..... 
      - npm test

  build:
    commands:
      # Building.....
      - npm run build
artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - "**/*"
  discard-paths: no
  base-directory: build