version: 0.2

phases: 
  install:
    commands:
      - Installing Node 18......
      - npm install
      # - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      # - apt install -y nodejs
  build:
    commands:
      - Testing..... 
      - npm test
      - Building.....
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public